name: Gradle Build

on:
  push:
    branches:
      - production

jobs:
  deploy-production:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          clean: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Create local.properties file
        run: echo PROPERTY_SECRET=property_test >> local.properties
      - name: Export environment variables
        run: |
          echo "VERSION_NAME=$(cat app/build/outputs/app_versioning/release/version_name.txt)" >> $GITHUB_ENV
          echo "VERSION_CODE=$(cat app/build/outputs/app_versioning/release/version_code.txt)" >> $GITHUB_ENV
      # skip actually pushing the build if the diff is zero because this means its a merge-back and
      # we'll get a conflict because the commits hasn't increased
      - uses: technote-space/get-diff-action@v6
        with:
          GET_FILE_DIFF: true
          DIFF_FILTER: 'AMRCD'
      - name: Build and Publish Release
        env:
          GH_USER: ${{ secrets.GH_USER }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: ./gradlew clean --no-build-cache publishProductionPublicationToGithubPackagesRepository
        if: env.GIT_DIFF
