name: Gradle Build

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:

    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Create local.properties file
        run: echo PROPERTY_SECRET=property_test >> local.properties
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Build with Gradle
        run: ./gradlew clean build --no-build-cache
      - name: lint
        run: ./gradlew app:lint
      - name: lint results
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: app/build/reports/lint/report.xml
      - name: Jvm Unit Tests with Coverage Report
        run: ./gradlew jacocoTestReportDebug
      - name: Clean Packages
        run: bash ./scripts/clean-packages.sh
      - name: On-Device Instrumented Tests
        run: ./gradlew connectedCheck
      - uses: actions/upload-artifact@v3
        name: Store Reporting Artifacts
        if: failure()
        with:
          name: app-reports
          path: |
            app/build/reports
            app/build/outputs

      - name: cleanup adb
        if: always()
        run: adb kill-server

      - name: Upload Unit Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./app/build/reports/jacoco/jacocoTestReportDebug/jacocoTestReportDebug.xml

      - name: Upload Instrumented Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: instrumentedtests
          files: ./app/build/reports/coverage/androidTest/debug/connected/report.xml

      # https://github.com/actions/checkout/issues/715
      # https://github.com/actions/checkout/pull/579
      - name: clean local tags
        if: always()
        run: |
          cd /tmp/hello-kotlin-android/hello-kotlin-android/hello-kotlin-android && 
          git config --global --add safe.directory /tmp/hello-kotlin-android/hello-kotlin-android/hello-kotlin-android &&
          git tag -d $(git tag -l)