name: Test and Reports

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:

    runs-on: self-hosted
    environment:
      name: dev
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clean: true
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Display host of runner
        run: echo $HOST_NAME
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Create local.properties file
        run: echo PROPERTY_SECRET=property_test >> local.properties
      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Build with Gradle
        run: ./gradlew clean build --no-build-cache
      - name: lint
        run: ./gradlew app:lint
      - name: lint results
        uses: yutailang0119/action-android-lint@v5.0.0
        with:
          report-path: app/build/reports/lint/report.xml
      - name: JVM unit Tests with Coverage Report
        run: ./gradlew check
      - name: Clean Packages
        run: bash ./scripts/clean-packages.sh
      - name: On-Device Instrumented Tests
        run: ./gradlew connectedCheck
      - uses: actions/upload-artifact@v4
        name: Store Reporting Artifacts
        if: failure()
        with:
          name: app-reports
          path: |
            app/build/reports
            app/build/outputs

      - name: Upload Lib Unit Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: libunittests
          files: ./lib/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Upload App Unit Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./app/build/reports/jacoco/jacoco.xml

      - name: Upload Instrumented Tests Report to CodeCov
        # https://github.com/codecov/codecov-action
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: instrumentedtests
          files: ./app/build/reports/coverage/androidTest/debug/connected/report.xml
